-- DECISION A2 (ASSET HEALTH)--  Lower Level

-- A2. Asset Health: The hospital needs to check the condition of the panel temperature sensor, as it helps in providing early warning signs of overheating, 
-- malfunctions, or deteriorating performance of the in-roof solar panel. Does the panel temperature sensor need to be replaced? If so, which sensor must 
-- be replaced? The sensor should be replaced if it is more than five years old and records an incorrect temperature value (temperature below 0 or above 65 
-- or generates null data). Provide the sensor's details and the date of the record when the error value is first generated by the sensor.

select * from ucesafs.sensor_error;

-----------------------------------------------------------------------

-- DECISION A1 (ASSET HEALTH)--  Middle Level

-- A1. Asset Health: To ensure sufficient energy production for the hospital, the hospital needs to check the condition of the panels. Does the hospital 
-- need to replace any in-roof solar panels this year? A panel must be replaced if it has been in use for more than 5 years, its average physical condition 
-- is equal to or more than "poor—cracks, significant scratches, moderate soiling, renewal required," and it has experienced overheating more than 10 times 
-- since the solar panel was first installed. If yes, provide the in-roof solar panel details.

select * from ucesafs.solar_panel_renewal;

-----------------------------------------------------------------------

-- DECISION E2 (ENERGY PRODUCTION)-- Top Level

-- E2. Energy Production: This year, the hospital is striving to achieve its goal of fulfilling 30% of its annual electricity needs through solar energy. 
-- Has the solar energy produced enough to meet the hospital's energy target? Give information on the annual energy generated by in-roof solar panels. 
-- Does the hospital need to add more in-house solar panels?

select * from ucesafs.annual_energy_production;

-----------------------------------------------------------------------

-- DECISION E1 (ENERGY PRODUCTION)-- Top Level

-- E1. Energy Production: The hospital intends to increase the production of its solar energy. Unfortunately, due to a restricted budget, the hospital 
-- intends to add more in-roof solar panels to fill the empty space in just one of its buildings. For this plan, buildings with lower energy production 
-- will be chosen. By calculating the energy produced by every building, the hospital can decide whether to execute the plan in building A or building B 
-- first. Provide the empty area of the chosen building and the number of solar panels that could be installed in that building.

-- 1. Get the building that produces the lowest energy from view ucesafs.energy_production_per_building
with
chosen_building as (select a.building_name, a.hospital_buildings_id, a.total_output_building_in_kWh, a.location, st_area(st_force2d(st_envelope(a.location))) 
as area from ucesafs.energy_production_per_building a where a.total_output_building_in_kWh = (select min(a.total_output_building_in_kWh) as lowest 
from ucesafs.energy_production_per_building a)),

-- 2. Calculate the area of one in-roof solar panel
area_per_panel as (select avg(st_area(location)) as area_panel from ucesafs.solar_panels where building_id = (select hospital_buildings_id from chosen_building)),

-- 3. Calculate the total area of existing solar panel at the chosen building
existing_area as (select sum(st_area(location)) as total_area_existing_solar_panel from ucesafs.solar_panels where building_id = (select hospital_buildings_id from chosen_building)),

-- 4. Calculate the empty area on the roof and the estimated number of in-roof solar panels that could be installed
difference_area as (select round((a.area - b.total_area_existing_solar_panel)::numeric, 2) as empty_area_in_m2, round(((a.area - b.total_area_existing_solar_panel) / c.area_panel)::numeric, 0) as estimated_number_of_solar_panel_could_be_installed from chosen_building a, existing_area b , area_per_panel c)

-- 5. Get the all details from the previous tables
select a.hospital_buildings_id, a.building_name, a.total_output_building_in_kWh as total_energy_produces_in_kWh, b.*, a.location as building_location from chosen_building a, difference_area b;

-- ====================================================
-- PYRAMID DECISIONS - RENEWAL ASSET COST
-- ====================================================

-- LOWER LEVEL (Decision B3)

-- B3. Budget and Cost: Based on the condition of the panel temperature sensor, if there is any sensor that needs to be replaced, what is the cost per panel 
-- temperature sensor? Using this information, we could see that the cost of replacing the panel temperature sensor still falls within the allocated budget, 
-- or does the hospital need to allocate more to it?

select * from ucesafs.cost_sensor_renewal;
-----------------------------------------------------------------------

-- LOWER LEVEL-MIDDLE LEVEL (Decision B2)

-- B2. Budget and Cost: How much would it cost per solar panel overall if any of the in-roof solar panels and panel temperature sensors needed to be replaced 
-- because of their condition? Finding this information is necessary so that the hospital can determine which solar panels need to be replaced first.

select * from ucesafs.total_cost_solar_panel_renewal;

-----------------------------------------------------------------------

-- MIDDLE LEVEL-TOP LEVEL (Decision B3)

-- B1. Budget and Cost: The hospital needs to find the total cost needed per hospital building this year to renew all assets that need to be replaced and 
-- then calculate the remaining budget. Using this information, the hospital can decide whether to reduce the budget allocated for the replacement of sensors 
-- and solar panels the following year or not. The budget for this could be lowered the following year if the residual amount is more than 30%.

select * from ucesafs.total_renewal_cost_per_building;